### ISSUE TITLE
Apple Crashes Application

### ISSUE THREAD

**Issue by BrayanVillatoro** [Ounceleopard/ATGS#1]
Termination Reason:    Namespace TCC, Code 0 
This app has crashed because it attempted to access privacy-sensitive data without a usage description. The app's Info.plist must contain an com.apple.security.device.camera key with a string value explaining to the user how the app uses this data.
<img width="859" alt="Screenshot 2023-09-24 at 10 09 49 PM" src="https://github.com/Ounceleopard/ATGS/assets/40043757/bd7d745f-ae8b-48e7-9688-05122b6b0736">

**Comment by Ounceleopard** [comment]
Directory structure should look like this: 

ATGS.app/
├── Contents/
│   ├── Info.plist
│   └── MacOS/
│       └── Drone-Feed.py
└── Resources/
    └── (other resources if needed)

**Comment by BrayanVillatoro** [comment]
Directory structure should look like this:

ATGS.app/
├── Contents/
│ ├── Info.plist
│ └── MacOS/
│ └── Drone-Feed.py
└── Resources/
└── (other resources if needed)

**Comment by BrayanVillatoro** [comment]
<img width="804" alt="Screenshot 2023-09-24 at 11 18 40 PM" src="https://github.com/Ounceleopard/ATGS/assets/40043757/acbf2014-fbd9-47a8-98b6-71cbad322f52">
info.plist file should look like this:

**Comment by BrayanVillatoro** [comment]
Set Executable Permission: In the terminal, navigate to the directory containing your app bundle and make your Python script executable by running the following command:
1. open a terminal at your file location then
chmod +x Contents/MacOS/Drone-Feedpy

can run it from the terminal:
./ATGS.app/Contents/MacOS/Drone-Feed.py
This should execute your Python script as a macOS application.
